dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  matrix:
  - COQ_IMAGE="coqorg/coq:8.8.2"
  - COQ_IMAGE="coqorg/coq:8.9"
  - COQ_IMAGE="coqorg/coq:8.9.1"
  - COQ_IMAGE="coqorg/coq:8.11.1"


script:
- echo -e "${ANSI_YELLOW}Building Coq code...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- docker build --build-arg=coq_image="${COQ_IMAGE}" --pull -t nn-opt .
- echo -en 'travis_fold:end:script\\r'
